### ISSUE TITLE
Open CMD log as a new tab. 

### ISSUE THREAD

**Issue by shivajivarma** [supnate/command-pad#10]
Hi.. Command pad is very cool tool, specially for developers who need to run build commands too often.

It would be really helpful, if i can click and open the wide log screen (its difficult to hover and scroll, in case of build failure or task failure, to analyze the log).

![image](https://cloud.githubusercontent.com/assets/1388742/23493389/8a32ca82-ff31-11e6-91ac-e2b2598608ff.png)

**Comment by supnate** [comment]
Thanks @shivajivarma for the feedback. Looks like a good enhancement candidate.

**Comment by supnate** [comment]
Now it has a fixed output panel.
