### ISSUE TITLE
Task does not finish on macOS 10.13.3

### ISSUE THREAD

**Issue by Pdobry** [supnate/command-pad#18]
When running any task (other that just simple 'ls -al') the task ends but Command Pad never notice that terminal exit and keeps icon in "running" state forever.

**Comment by supnate** [comment]
I can't reproduce it by adding a command `ls -al`. It notifies and icon back to gray. Could you provide more info?

**Comment by supnate** [comment]
Such as your command config screenshot.

**Comment by Pdobry** [comment]
I wrote "other than just simple ls -al". Try something that takes few seconds to complete. I can reproduce it with just "sleep 3" command.
<img width="567" alt="screen shot 2018-03-28 at 11 07 39" src="https://user-images.githubusercontent.com/5190625/38019586-4b998664-3278-11e8-9f5e-94785658dd67.png">

**Comment by Pdobry** [comment]
Suprisingly enough, I found. workaround. When you wrap a command that takes more than few seconds to "time" command (eg. "time sleep 3") then it works fine.

**Comment by supnate** [comment]
Sorry that I misunderstood the case... But `sleep 3` still works for me, without "time" before it.

**Comment by Pdobry** [comment]
It seems to be resolved by yesterday's update to macOS 10.13.4. Works fine now.
