### ISSUE TITLE
勾选弹窗提示貌似没啥反应

### ISSUE THREAD

**Issue by jing2si** [supnate/command-pad#2]
环境：windows 10 企业版
![image](https://cloud.githubusercontent.com/assets/2288824/19674274/911dfa92-9ab9-11e6-9485-ecebe9c835e8.png)
已勾选上面这个，但是命令执行完后没任何提示。

**Comment by supnate** [comment]
确实是个 bug，windows 上无法提示，下个版本修复。感谢报告！

**Comment by supnate** [comment]
已在 master 上修复。
