### ISSUE TITLE
execvp(3) failed.: Operation not permitted

### ISSUE THREAD

**Issue by yy8597** [supnate/command-pad#4]
只是运行了npm start，就报错execvp(3) failed.: Operation not permitted。

**Comment by supnate** [comment]
Is the app downloaded from App Store or from GitHub? If the former, it runs in the sandbox so there's no permission to run arbitrary commands, you should download the dmg from GitHub. Otherwise maybe there's permission issue of your npm installation. Try check `sudo` to run the command again.

**Comment by yy8597** [comment]
我是从App store上安装的。我现在直接从github下载，不报错了...
