### ISSUE TITLE
execvp(3) failed.: Operation not permitted

### ISSUE THREAD

**Issue by tobsn** [supnate/command-pad#5]
With or without sudo I'm always getting:
`execvp(3) failed.: Operation not permitted`

El Capitan latest

**Comment by supnate** [comment]
As mentioned in the description on the Mac App Store, it's sandboxed by Apple so it doesn't have permission to run arbitrary command. Please download a full-featured version at: https://github.com/supnate/command-pad/releases

**Comment by tobsn** [comment]
ah... so my guess was right... but yeah, I didn't read that... thanks!
