### ISSUE TITLE
execvp(3) failed.: No such file or directory

### ISSUE THREAD

**Issue by zhoulijie** [supnate/command-pad#6]
提示 `execvp(3) failed.: No such file or directory` 
`MAC OS 10.11.6`,我是通过nvm管理的nodejs，和nvm有关系吗？

![image](https://cloud.githubusercontent.com/assets/4424050/20552058/d934f8ba-b181-11e6-9d13-f5dc37258b90.png)

![image](https://cloud.githubusercontent.com/assets/4424050/20552062/e7994cf8-b181-11e6-8b0f-a535d179ce6d.png)

**Comment by supnate** [comment]
如果用 nvm，需要在 setting 里设下需要版本的路径：Environment path，例如：/Users/nate/.nvm/versions/node/v6.8.1/bin:/Users/i305656/.yarn/bin

**Comment by zhoulijie** [comment]
太棒了。解决了！多谢！
