### ISSUE TITLE
Problem running a `yarn`command

### ISSUE THREAD

**Issue by martinratinaud** [supnate/command-pad#9]
Hi and thanks for this awesome tool.

It would be super nice if we could use yarn in `Command` section because whenever I do so, I get a `execvp(3) failed.: No such file or directory`

Maybe it's because I misconfigured the environment path variable.
What I use today is `/Users/martin/.nvm/versions/node/v7.5.0`

Hope you can help and thanks again

**Comment by supnate** [comment]
Thanks @martinratinaud 
You may need to add `yarn` path to the env path like: `/Users/martin/.nvm/versions/node/v7.5.0:/usr/local/bin`. It assumes the `yarn` command is under `/usr/local/bin/yarn`.

Run `which yarn` to find your yarn path.

**Comment by martinratinaud** [comment]
Thanks a lot, in fact, I add to put

`/Users/martin/.nvm/versions/node/v7.5.0/bin/`

and everything's alright now, maybe it would be nice to add it to `src/features/home/SettingsPage.js` in help message

Instead of "The environment path to find the command. You may need to set this when using nvm."

could be 

"The environment path to find the command. You may need to set this when using nvm. i.e. /path/to/.nvm/versions/node/<version>/bin"

Thanks anyway, I close this one

**Comment by supnate** [comment]
Ok, no problem. I will refine the tooltip.
